#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GetDone.Resource", IsApplication=true)]

namespace GetDone
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int barber = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int GetDone = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Tailor = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Tattoo = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int EmailIn = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int FName = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int LName = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int Password = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int SignUp = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Signin = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int edittext = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int edittext1 = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Login = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SignIn = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Signup = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
